export const GLOBALTYPES = {
    AUTH: "AUTH",
    ALERT: "ALERT",
    UPDATE_TOKEN: "UPDATE_TOKEN",
    SOCKET: "SOCKET",
    MODAL: 'MODAL',
    ONLINE: 'ONLINE',
    OFFLINE: 'OFFLINE',
    GET_USERS_ONLINE: 'GET_USERS_ONLINE'
}