export const MESSAGE_TYPES = {
    GET_CONVERSATIONS: 'GET_CONVERSATIONS',
    GET_MESSAGES: 'GET_MESSAGES',
    UPDATE_MESSAGES: 'UPDATE_MESSAGES',
    CREATE_CONVERSATION: 'CREATE_CONVERSATION',
    UPDATE_CONVERSATION: 'UPDATE_CONVERSATION',
    UPDATE_LAST_MESSAGE: 'UPDATE_LAST_MESSAGE',
    CREATE_MESSAGE: 'CREATE_MESSAGE',
    UPDATE_NAME_CONVERSATION: 'UPDATE_NAME_CONVERSATION',
    UPDATE_THUMBNAIL_CONVERSATION: 'UPDATE_THUMBNAIL_CONVERSATION',
}